version: "3"

services:     
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=somepassword
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:81
    #command: bash -c "sleep infinity"
    volumes:
      - ./django:/code/
    ports:
      - "81:81"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=somepassword
