# Generated by Django 2.2.13 on 2021-01-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BashPrompts',
            new_name='BashPrompt',
        ),
    ]
