# Generated by Django 2.2.13 on 2021-01-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0002_auto_20210110_1926'),
    ]

    operations = [
    ]

def create_dummy_bpms(apps, schema_editor):
    BashPrompt = apps.get_model('bpm', 'BashPrompt')

    BashPrompt(name='mattw@laptop', value='$mattw@laptop').save()
    BashPrompt(name='[mattw]@(laptop) [$]', value='$hostname').save()
    BashPrompt(name='$', value='asdf').save()

class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_bpms),
    ]
