# Generated by Django 2.2.13 on 2021-01-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0002_auto_20210110_1926'),
        ('bpm', '0003_dummy_bpm'),
    ]

    operations = [
    ]
